name: Show latest crypto data

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '40 * * * *'
      
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('ries9112/PredictCrypto')"
          Rscript -e "install.packages(c('pins', 'ggplot2','anytime','ggthemes','fs'))"
      - name: Run script
        run: |-
          Rscript -e "source('script.R')"
      - name: Commit files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git add .
          git commit -m "Update GitHub readme" -a
      - name: Push
        run: |-
          Rscript -e "system('git push origin master')"


