name: Hourly Update Chart GIF

on:
  push:
    branches: [master]
  schedule:
    - cron:  '15 * * * *'
      
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Packages and Run Script
        run: |-
          Rscript -e "install.packages('devtools')"
          Rscript -e "install.packages(c('pins','ggplot2','anytime','ggthemes','magick','gganimate','dplyr','togglr'))"
          Rscript -e "source('script.R')"
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Commit and push files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git add .
          git commit -m "Update GitHub readme" -a
          git push https://ries9112:${{secrets.GITHUB_TOKEN}}@github.com/ries9112/ries9112.git HEAD:master --force
